[package]
name = "waterbird"
version = "0.1.0"
edition = "2024"

[dependencies]
autarkie = { version = "0.7.0", features = ["derive", "libfuzzer"] }
lalrpop-util = {version = "0.22.2", features = ["lexer"]}
rustc-hash = "2.1.1"
serde = { version = "1.0.228", features = ["derive"] }
slab = "0.4.11"
unescaper = "0.1.6"

[build-dependencies]
lalrpop = {version = "0.22.2"}

[[bin]]
name = "typechecker"
