[package]
name = "waterbird-fuzz"
version = "0.0.0"
publish = false
edition = "2024"

[package.metadata]
cargo-fuzz = true

[dependencies]
bincode = "1"
libfuzzer-sys = { package = "autarkie_libfuzzer", version = "0.9.4" }

[dependencies.waterbird]
path = ".."


[[bin]]
name = "autarkie_harness"
path = "fuzz_targets/autarkie_harness.rs"
test = false
doc = false
bench = false
